export enum STEPS {
  'BASIC_INFO' = 0,
  'REVIEW_INFO' = 1,
  'SUCCESS' = 2,
  'ERROR' = 3,
}

export enum BASIC_INFO {
  'INITIAL' = 0,
  'INITIAL_AND_SHOWING_ERROR' = 1,
  'USER_CREATED' = 2,
  'USER_CREATED_AND_SHOWING_ERROR' = 3,
  'COMPLETED' = 4,
}

export enum WORK_INFO {
  'INITIAL' = 0,
  'INITIAL_AND_SHOWING_ERROR' = 1,
  'COMPLETED' = 2,
}
