export const typography = {
  pxToRem: size => `${(size / 10) * 1}rem`,
  htmlFontSize: 16,
  // fontFamily: '"Kanit", "Inter", "Helvetica", "Arial", sans-serif',
  // fontSize: 14,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 600,
  h1: {
    fontFamily: '"Kanit", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: 32,
    lineHeight: '126%',
    letterSpacing: '-0.25px',
  },
  h2: {
    fontFamily: '"Kanit", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: 24,
    lineHeight: '132%',
    letterSpacing: '0px',
  },
  h3: {
    fontFamily: '"Kanit", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: 20,
    lineHeight: '140%',
    letterSpacing: '0.25px',
  },
  h4: {
    fontFamily: '"Kanit", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '150%',
    letterSpacing: '0.5px',
  },
  h5: {
    fontFamily: '"Kanit", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: 14,
    lineHeight: 1.334,
    letterSpacing: '0em',
  },
  h6: {
    fontFamily: '"Kanit", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: 14,
    lineHeight: 1.6,
    letterSpacing: '0.0075em',
  },
  subtitle1: {
    // fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '150%',
    letterSpacing: '0.5px',
  },
  body1: {
    // fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '150%',
    letterSpacing: '0.5px',
  },
  subtitle2: {
    // fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '146%',
    letterSpacing: '0.75px',
  },
  body2: {
    // fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '146%',
    letterSpacing: '0.75px',
  },
  button: {
    fontFamily: '"Kanit", "Helvetica", "Arial", sans-serif',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: '146%',
    letterSpacing: '0.75px',
  },
  buttonLink: {
    fontFamily: '"Kanit", "Helvetica", "Arial", sans-serif',
    fontWeight: 500,
    fontSize: 16,
    lineHeight: '146%',
    letterSpacing: '0.5px',
  },
  caption: {
    fontFamily: '"Kanit", "Helvetica", "Arial", sans-serif',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '132%',
    letterSpacing: '1px',
  },
  overline: {
    fontFamily: '"Kanit", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: 12,
    lineHeight: 2.66,
    letterSpacing: '0.08333em',
  },
};
